services:
  traefik:
    image: traefik:v3.0
    command:
      - --api.insecure=true      
      - --entrypoints.web.address=:80
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --providers.swarm=true
      - --providers.swarm.exposedbydefault=false
    ports:
      - "8888:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - lbnetwork
    deploy:
      placement:
        constraints: [node.role == manager]

networks:
  lbnetwork:
    external: true